//! Binoculars-family AI-origin detection: a two-model perplexity ratio.
//!
//! The Binoculars method (Hans et al. 2024) scores a text with two models and
//! flags machine text because it is predictable to both in a way the ratio
//! exposes. This is the tractable variant: it uses the actual-token
//! cross-entropies rather than the full-distribution cross-entropy of the paper,
//! so it is a Binoculars-FAMILY signal. It answers "was this generated by a
//! model", not "which watermark is present", and it is reported as PROBABLE
//! (calibrated, with a false-positive rate), never as proof.

use crate::analyze::{analyze, AnalyzeOptions, Finding, Verdict, WordmarkReport};
use crate::backend::BackendError;
use crate::logprob::{mean_neg_logprob, LogprobProvider};

/// The ratio of the observer model's cross-entropy on a text to the performer
/// model's. A lower ratio leans machine-generated. `None` when either sequence
/// is empty or the performer cross-entropy is zero.
pub fn binoculars_score(observer_logprobs: &[f64], performer_logprobs: &[f64]) -> Option<f64> {
    let observer = mean_neg_logprob(observer_logprobs)?;
    let performer = mean_neg_logprob(performer_logprobs)?;
    if performer <= 0.0 {
        return None;
    }
    Some(observer / performer)
}

/// Score a text with two logprob providers (two models).
pub fn binoculars<O, P>(observer: &O, performer: &P, text: &str) -> Result<f64, BackendError>
where
    O: LogprobProvider,
    P: LogprobProvider,
{
    let observer_logprobs = observer.sequence_logprobs(text)?;
    let performer_logprobs = performer.sequence_logprobs(text)?;
    binoculars_score(&observer_logprobs, &performer_logprobs).ok_or(BackendError::Empty)
}

/// Produce the AI-origin finding for the analysis report: PROBABLE by nature, a
/// calibrated keyless signal and not a certainty.
pub fn binoculars_finding<O, P>(observer: &O, performer: &P, text: &str) -> Result<Finding, BackendError>
where
    O: LogprobProvider,
    P: LogprobProvider,
{
    let score = binoculars(observer, performer, text)?;
    Ok(Finding {
        verdict: Verdict::Probable,
        label: "ai-origin".to_string(),
        detail: format!(
            "Binoculars-family perplexity ratio {score:.3}; a lower ratio leans machine-generated. \
             Calibrated detection needs a matched model pair, and this is reported as probable, never proof."
        ),
    })
}

/// Run the pure-Rust analysis and add the Binoculars AI-origin finding on top,
/// so the report carries the model-based signal alongside the certain findings.
/// The AI-origin finding is placed first; the structural-wall finding stays.
pub fn analyze_with_ai_origin<O, P>(
    text: &str,
    opts: &AnalyzeOptions,
    observer: &O,
    performer: &P,
) -> WordmarkReport
where
    O: LogprobProvider,
    P: LogprobProvider,
{
    let mut report = analyze(text, opts);
    if let Ok(finding) = binoculars_finding(observer, performer, text) {
        report.findings.insert(0, finding);
    }
    report
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::logprob::mock::MockLogprobs;

    #[test]
    fn score_is_the_cross_entropy_ratio() {
        // observer cross-entropy 2.0, performer 1.0, so the ratio is 2.0.
        assert_eq!(
            binoculars_score(&[-2.0, -2.0, -2.0], &[-1.0, -1.0, -1.0]),
            Some(2.0)
        );
        // Empty or degenerate inputs yield no score.
        assert_eq!(binoculars_score(&[], &[-1.0]), None);
        assert_eq!(binoculars_score(&[-1.0], &[0.0]), None);
    }

    #[test]
    fn binoculars_over_providers_uses_their_logprobs() {
        let observer = MockLogprobs(vec![-2.0, -2.0]);
        let performer = MockLogprobs(vec![-1.0, -1.0]);
        assert_eq!(binoculars(&observer, &performer, "any text").unwrap(), 2.0);
    }

    #[test]
    fn the_ai_origin_finding_is_probable_and_labeled() {
        let observer = MockLogprobs(vec![-2.0, -2.0]);
        let performer = MockLogprobs(vec![-1.0, -1.0]);
        let finding = binoculars_finding(&observer, &performer, "any text").unwrap();
        assert_eq!(finding.verdict, Verdict::Probable);
        assert_eq!(finding.label, "ai-origin");
    }

    #[test]
    fn analysis_integrates_the_ai_origin_finding() {
        let observer = MockLogprobs(vec![-2.0, -2.0]);
        let performer = MockLogprobs(vec![-1.0, -1.0]);
        let report = analyze_with_ai_origin(
            "just some plain ordinary words here",
            &AnalyzeOptions::default(),
            &observer,
            &performer,
        );
        // The report now carries a probable AI-origin finding and still names
        // the structural wall.
        assert!(report
            .findings
            .iter()
            .any(|f| f.verdict == Verdict::Probable && f.label == "ai-origin"));
        assert!(report.findings.iter().any(|f| f.verdict == Verdict::Impossible));
    }

    /// Live check with two real models. Ignored by default: set
    /// STEGANO_WM_TEST_MODEL and STEGANO_WM_TEST_MODEL2 to GGUF paths and run
    /// with `--features embedded-llama -- --ignored`.
    #[cfg(feature = "embedded-llama")]
    #[test]
    #[ignore = "needs two real GGUFs (STEGANO_WM_TEST_MODEL, STEGANO_WM_TEST_MODEL2)"]
    fn live_binoculars_over_two_real_models() {
        use crate::EmbeddedLlamaBackend;
        let m1 = std::env::var("STEGANO_WM_TEST_MODEL").expect("set STEGANO_WM_TEST_MODEL");
        let m2 = std::env::var("STEGANO_WM_TEST_MODEL2").expect("set STEGANO_WM_TEST_MODEL2");
        let observer = EmbeddedLlamaBackend::load(&m1, "x").expect("model 1 loads");
        let performer = EmbeddedLlamaBackend::load(&m2, "x").expect("model 2 loads");
        let score = binoculars(
            &observer,
            &performer,
            "The quick brown fox jumps over the lazy dog and then runs away.",
        )
        .expect("both models score the text");
        assert!(score.is_finite() && score > 0.0, "binoculars score {score}");
    }
}
